import fs from 'fs/promises';
import path from 'path';

export interface SDKValidationResult {
  valid: boolean;
  sdkName: string;
  sdkBasePath: string;
  includeDir?: string;
  libDir?: string;
  errors: string[];
  warnings: string[];
}

const AMD_BASE = 'C:\\AMD\\2025.2';

/**
 * Validates SDK availability for the Zynq reference platform.
 * For AMD/Xilinx: verifies that the Vitis standalone BSP has been generated
 * (the BSP include/lib directories produced by 'platform generate' in XSCT).
 * 
 * IMPORTANT: Does NOT generate fake headers or SDK stubs.
 * If the SDK is missing, it returns valid=false with a clear error.
 */
export async function validateXilinxSDK(
  workspace: string,
  procName: string,
  isZynq7000: boolean
): Promise<SDKValidationResult> {
  const errors: string[] = [];
  const warnings: string[] = [];

  const sdkBasePath = path.join(
    workspace, 'vitis_ws', 'my_platform', procName, 'standalone_domain', 'bsp', procName
  );
  const includeDir = path.join(sdkBasePath, 'include');
  const libDir = path.join(sdkBasePath, 'lib');

  // Check if BSP was generated by XSCT
  let includeExists = false;
  let libExists = false;
  try { await fs.access(includeDir); includeExists = true; } catch { /* not present */ }
  try { await fs.access(libDir); libExists = true; } catch { /* not present */ }

  if (!includeExists) {
    errors.push(
      `Vitis BSP include directory not found: ${includeDir}\n` +
      `  Cause: XSCT 'platform generate' step has not completed successfully.\n` +
      `  Resolution: Ensure XSCT ran successfully and the Vivado XSA export succeeded.`
    );
  }

  if (!libExists) {
    errors.push(
      `Vitis BSP lib directory not found: ${libDir}\n` +
      `  Cause: XSCT 'platform generate' step has not completed successfully.\n` +
      `  Resolution: Ensure XSCT ran successfully and the Vivado XSA export succeeded.`
    );
  }

  // If BSP exists, verify critical SDK headers are present
  if (includeExists) {
    const criticalHeaders = ['xil_types.h', 'xparameters.h'];
    for (const h of criticalHeaders) {
      try {
        await fs.access(path.join(includeDir, h));
      } catch {
        warnings.push(`Expected SDK header '${h}' not found in BSP include directory. The BSP may be incomplete.`);
      }
    }
  }

  // Check that GCC toolchain itself is installed (separate from BSP)
  const gccPath = isZynq7000
    ? `${AMD_BASE}\\Vitis\\gnu\\aarch32\\nt\\gcc-arm-none-eabi\\bin\\arm-none-eabi-gcc.exe`
    : `${AMD_BASE}\\Vitis\\gnu\\aarch64\\nt\\aarch64-none\\bin\\aarch64-none-elf-gcc.exe`;

  try {
    await fs.access(gccPath);
  } catch {
    errors.push(
      `GCC compiler not found: ${gccPath}\n` +
      `  Resolution: Ensure AMD Vitis 2025.2 is properly installed.`
    );
  }

  const valid = errors.length === 0;

  return {
    valid,
    sdkName: 'AMD Vitis Standalone BSP (Xilinx)',
    sdkBasePath,
    includeDir: includeExists ? includeDir : undefined,
    libDir: libExists ? libDir : undefined,
    errors,
    warnings,
  };
}
