export enum ErrorCategory {
  RTL_SYNTAX_ERROR = 'RTL_SYNTAX_ERROR',
  UNBOUND_MODULE = 'UNBOUND_MODULE',
  UNSUPPORTED_CONSTRUCT = 'UNSUPPORTED_CONSTRUCT',
  SYNTHESIS_FAILURE = 'SYNTHESIS_FAILURE',
  TIMING_VIOLATION = 'TIMING_VIOLATION',
  MEMORY_OVERFLOW = 'MEMORY_OVERFLOW',
  TOOL_NOT_FOUND = 'TOOL_NOT_FOUND',
  TOOL_EXECUTION_FAILED = 'TOOL_EXECUTION_FAILED',
  UNDEFINED_SYMBOL = 'UNDEFINED_SYMBOL',
  SIMULATION_CRASH = 'SIMULATION_CRASH',
  INVALID_CONSTRAINTS = 'INVALID_CONSTRAINTS',
  PIN_MAPPING_MISMATCH = 'PIN_MAPPING_MISMATCH'
}

export interface ErrorDetail {
  category: ErrorCategory;
  message: string;
  file?: string;
  line?: number;
  column?: number;
  tool: string;
  rawOutput?: string;
  fatal: boolean;
}
