import { ITemplateEngine } from './ITemplateEngine';

export class BareMetalTemplateEngine implements ITemplateEngine {
  public readonly id = 'template-baremetal-c';
  public readonly name = 'Bare-Metal C/ASM Source Code Template Engine';
  public readonly supportedOS = ['bare_metal', 'freertos'];

  public render(templateName: string, context: Record<string, any>): string {
    const procId = context.targetProcessorId || 'zynq-7000';
    const uartAddr = context.uartBaseAddress || '0x41200000';

    if (templateName === 'system_init.c') {
      return `/* Automatically generated by IBFGE Platform Generator v2.0 */
#include "board.h"
#include "clock.h"

void SystemInit(void) {
    /* Initialize PLL Clocks & Fabric Clock 0 */
    SystemClock_Config();
    
    /* Initialize Peripheral Base Address Registers */
    UART_Init(${uartAddr});
}
`;
    }

    if (templateName === 'startup.S') {
      return `/* Startup Code for ARM Cortex / RISC-V */
.syntax unified
.global Reset_Handler
.type Reset_Handler, %function

Reset_Handler:
    ldr r0, =_estack
    mov sp, r0
    bl SystemInit
    bl main
1:  b 1b
`;
    }

    if (templateName === 'linker.ld') {
      return `/* Linker Script for ${procId} */
MEMORY
{
    FLASH (rx)  : ORIGIN = 0x00000000, LENGTH = 256K
    SRAM  (rwx) : ORIGIN = 0x00100000, LENGTH = 512M
}

SECTIONS
{
    .text : { *(.text*) } > SRAM
    .data : { *(.data*) } > SRAM
    .bss  : { *(.bss*)  } > SRAM
}
`;
    }

    return `/* Header Template: ${templateName} */\n#ifndef BOARD_H\n#define BOARD_H\n#define UART_BASE ${uartAddr}\n#endif\n`;
  }
}
