import type { PlatformPreset } from '../types';

export type { PlatformPreset };

const rawPresets: PlatformPreset[] = [
  {
    id: 'xilinx-zynq-7000',
    name: 'Xilinx Zynq-7000',
    vendor: 'Xilinx',
    logoType: 'xilinx' as const,
    architecture: 'ARM Cortex-A9 + FPGA',
    frequency: '667 MHz',
    peripherals: [
      { id: '1', peripheralBlock: 'gpio_0', physicalPinMapping: 'LEDs/Buttons', clockNetIndicator: false, baseAddress: '0x41200000', driverName: 'xgpio' },
      { id: '2', peripheralBlock: 'uartlite_0', physicalPinMapping: 'RX/TX Pins', clockNetIndicator: true, baseAddress: '0x40600000', driverName: 'xuartlite' },
      { id: '3', peripheralBlock: 'timer_0', physicalPinMapping: 'Timer Pins', clockNetIndicator: true, baseAddress: '0x41C00000', driverName: 'xtmrctr' },
      { id: '4', peripheralBlock: 'iic_0', physicalPinMapping: 'SCL/SDA', clockNetIndicator: true, baseAddress: '0x41600000', driverName: 'xiic' },
      { id: '5', peripheralBlock: 'spi_0', physicalPinMapping: 'MISO/MOSI/SCLK', clockNetIndicator: true, baseAddress: '0x44A00000', driverName: 'xspi' },
    ],
    bareMetalCode: `/**
 * Xilinx Zynq-7000 Bare Metal Driver
 * Generated by GenAI BSP Platform
 */

#include <stdint.h>
#include <stdbool.h>

#define UART1_BASE         0x41200000
#define GPIO_BASE           0x41210000
#define I2C0_BASE           0x41220000
#define SPI0_BASE           0x41230000
#define CAN0_BASE           0x41240000
#define ETH0_BASE           0x41250000
#define USB0_BASE           0x41260000
#define SD0_BASE            0x41270000

/* Simple Main Entry Point - Phase 9 Hardware Demo */
int main(void) {
    // 1. Initialize UART and print Hello World
    uint32_t* uart_ctrl = (uint32_t*)(UART1_BASE + 0x00);
    // (mock UART init)
    
    // 2. Initialize GPIO for LED blink
    uint32_t* gpio_dir = (uint32_t*)(GPIO_BASE + 0x04);
    uint32_t* gpio_out = (uint32_t*)(GPIO_BASE + 0x08);
    *gpio_dir = 0x1; // Set pin 0 to output
    
    while(1) {
        *gpio_out ^= 0x1; // Toggle LED
        for(volatile int i = 0; i < 1000000; i++); // Delay
    }
    return 0;
}`,
    deviceTreeCode: `/* Device Tree for Zynq-7000 */
/ {
    amba {
        serial@e0001000 {
            compatible = "xlnx,xps-uartlite-1.00.a";
            reg = <0xe0001000 0x1000>;
        };
    };
};`
  },
  {
    id: 'xilinx-zynq-mpsoc',
    name: 'Xilinx Zynq MPSoC',
    vendor: 'Xilinx',
    logoType: 'xilinx' as const,
    architecture: 'ARM Cortex-A53 + FPGA',
    frequency: '1.2 GHz',
    peripherals: [
      { id: '1', peripheralBlock: 'UART1', physicalPinMapping: 'MIO[48:49]', clockNetIndicator: true, baseAddress: '0xFF010000', driverName: 'xuartps' },
      { id: '2', peripheralBlock: 'GPIO', physicalPinMapping: 'MIO[0:31]', clockNetIndicator: true, baseAddress: '0xFF0A0000', driverName: 'xgpiops' },
      { id: '3', peripheralBlock: 'I2C0', physicalPinMapping: 'MIO[14:15]', clockNetIndicator: true, baseAddress: '0xFF020000', driverName: 'xiicps' },
      { id: '4', peripheralBlock: 'SPI0', physicalPinMapping: 'MIO[16:21]', clockNetIndicator: true, baseAddress: '0xFF040000', driverName: 'xspips' },
      { id: '5', peripheralBlock: 'CAN0', physicalPinMapping: 'MIO[22:23]', clockNetIndicator: false, baseAddress: '0xFF060000', driverName: 'xcanps' },
      { id: '6', peripheralBlock: 'ETH0', physicalPinMapping: 'MIO[32:43]', clockNetIndicator: true, baseAddress: '0xFF0B0000', driverName: 'xemacps' },
      { id: '7', peripheralBlock: 'USB0', physicalPinMapping: 'MIO[44:47]', clockNetIndicator: true, baseAddress: '0xFF9D0000', driverName: 'xusbps' },
      { id: '8', peripheralBlock: 'SD0', physicalPinMapping: 'MIO[50:55]', clockNetIndicator: true, baseAddress: '0xFF160000', driverName: 'xsdps' },
    ],
    bareMetalCode: `/**
 * Xilinx Zynq MPSoC Bare Metal Driver
 * Generated by GenAI BSP Platform
 */

#include <stdint.h>
#include <stdbool.h>

#define UART1_BASE         0xFF010000
#define GPIO_BASE           0xFF0A0000
#define I2C0_BASE           0xFF020000
#define SPI0_BASE           0xFF040000
#define CAN0_BASE           0xFF060000
#define ETH0_BASE           0xFF0B0000
#define USB0_BASE           0xFF9D0000
#define SD0_BASE            0xFF160000

/* UART Register Map */
typedef struct {
    volatile uint32_t CR;       /* Control Register */
    volatile uint32_t MR;       /* Mode Register */
    volatile uint32_t IER;      /* Interrupt Enable */
    volatile uint32_t IDR;      /* Interrupt Disable */
    volatile uint32_t IMR;      /* Interrupt Mask */
    volatile uint32_t ISR;      /* Interrupt Status */
    volatile uint32_t RXTXFIFO; /* RX/TX FIFO */
} UART_Regs;

/* GPIO Register Map */
typedef struct {
    volatile uint32_t DATA_RO;   /* Data Read-Only */
    volatile uint32_t DATA;      /* Data Output */
    volatile uint32_t DIRM;     /* Direction Mode */
    volatile uint32_t OUT_EN;   /* Output Enable */
    volatile uint32_t INT_EN;   /* Interrupt Enable */
    volatile uint32_t INT_DIS;  /* Interrupt Disable */
} GPIO_Regs;

static UART_Regs* uart1 = (UART_Regs*)UART1_BASE;
static GPIO_Regs* gpio = (GPIO_Regs*)GPIO_BASE;

void uart_init(uint32_t baud_rate) {
    uart1->CR = 0x00000017;  /* Enable TX/RX, reset */
    uart1->MR = 0x00000020;  /* Normal mode */
}

void uart_putc(char c) {
    while ((uart1->ISR & 0x00000010) == 0);
    uart1->RXTXFIFO = c;
}

void gpio_set_direction(uint32_t pin, bool is_output) {
    if (is_output) {
        gpio->DIRM |= (1U << pin);
        gpio->OUT_EN |= (1U << pin);
    } else {
        gpio->DIRM &= ~(1U << pin);
        gpio->OUT_EN &= ~(1U << pin);
    }
}

void gpio_write(uint32_t pin, bool value) {
    if (value) {
        gpio->DATA |= (1U << pin);
    } else {
        gpio->DATA &= ~(1U << pin);
    }
}

void system_init(void) {
    uart_init(115200);
    gpio_set_direction(0, true);
    gpio_write(0, true);

    char* msg = "[Zynq MPSoC] BSP Initialization Complete\\r\\n";
    while (*msg) uart_putc(*msg++);
}

int main(void) {
    system_init();
    while (1) {
        gpio_write(0, false);
        for (volatile int i = 0; i < 1000000; i++);
        gpio_write(0, true);
        for (volatile int i = 0; i < 1000000; i++);
    }
    return 0;
}`,
    deviceTreeCode: `/dts-v1/;
/ {
    compatible = "xlnx,zynqmp";
    model = "Xilinx Zynq MPSoC GenAI BSP";
    #address-cells = <2>;
    #size-cells = <2>;

    cpus {
        #address-cells = <1>;
        #size-cells = <0>;

        cpu@0 {
            device_type = "cpu";
            compatible = "arm,cortex-a53";
            reg = <0x0>;
            clock-frequency = <1200000000>;
        };
    };

    memory@0 {
        device_type = "memory";
        reg = <0x0 0x0 0x0 0x80000000>;
    };

    uart@ff010000 {
        compatible = "xlnx,zynqmp-uart", "cdns,uart-r1p12";
        reg = <0x0 0xff010000 0x0 0x1000>;
        interrupts = <0 53 0>;
        clock-names = "uart_clk", "pclk";
        status = "okay";
    };

    gpio@ff0a0000 {
        compatible = "xlnx,zynqmp-gpio";
        reg = <0x0 0xff0a0000 0x0 0x1000>;
        #gpio-cells = <2>;
        gpio-controller;
        status = "okay";
    };

    i2c@ff020000 {
        compatible = "cdns,i2c-r1p14";
        reg = <0x0 0xff020000 0x0 0x1000>;
        #address-cells = <1>;
        #size-cells = <0>;
        interrupts = <0 17 0>;
        clock-frequency = <400000>;
        status = "okay";
    };

    spi@ff040000 {
        compatible = "xlnx,zynqmp-spi";
        reg = <0x0 0xff040000 0x0 0x1000>;
        interrupts = <0 26 0>;
        #address-cells = <1>;
        #size-cells = <0>;
        status = "okay";
    };

    ethernet@ff0b0000 {
        compatible = "xlnx,zynqmp-gem";
        reg = <0x0 0xff0b0000 0x0 0x1000>;
        interrupts = <0 57 0>;
        phy-mode = "rgmii-id";
        status = "okay";
    };
};`,
  },
  {
    id: 'ti-sitara-am335x',
    name: 'TI Sitara AM335x',
    vendor: 'Texas Instruments',
    logoType: 'ti' as const,
    architecture: 'ARM Cortex-A8',
    frequency: '1.0 GHz',
    peripherals: [
      { id: '1', peripheralBlock: 'UART0', physicalPinMapping: 'PAD[96:99]', clockNetIndicator: true, baseAddress: '0x44E09000' },
      { id: '2', peripheralBlock: 'GPIO1', physicalPinMapping: 'PAD[4:15]', clockNetIndicator: true, baseAddress: '0x4804C000' },
      { id: '3', peripheralBlock: 'I2C1', physicalPinMapping: 'PAD[100:101]', clockNetIndicator: true, baseAddress: '0x4802A000' },
      { id: '4', peripheralBlock: 'SPI0', physicalPinMapping: 'PAD[102:105]', clockNetIndicator: true, baseAddress: '0x48030000' },
      { id: '5', peripheralBlock: 'MMC0', physicalPinMapping: 'PAD[140:147]', clockNetIndicator: true, baseAddress: '0x48060000' },
      { id: '6', peripheralBlock: 'GPMC', physicalPinMapping: 'PAD[160:185]', clockNetIndicator: false, baseAddress: '0x50000000' },
      { id: '7', peripheralBlock: 'McASP0', physicalPinMapping: 'PAD[106:111]', clockNetIndicator: true, baseAddress: '0x48038000' },
    ],
    bareMetalCode: `/**
 * Texas Instruments Sitara AM335x Bare Metal Driver
 * Generated by GenAI BSP Platform
 */

#include <stdint.h>
#include <stdbool.h>

#define UART0_BASE          0x44E09000
#define GPIO1_BASE          0x4804C000
#define I2C1_BASE           0x4802A000
#define SPI0_BASE           0x48030000

#define MMC0_BASE           0x48060000
#define GPMC_BASE           0x50000000
#define MCASP0_BASE         0x48038000

/* UART Register Map (16550 Compatible) */
typedef struct {
    volatile uint8_t RBR_THR;  /* RX Buffer / TX Holding */
    volatile uint8_t IER;      /* Interrupt Enable */
    volatile uint8_t FCR_IIR;   /* FIFO Control / Int ID */
    volatile uint8_t LCR;      /* Line Control */
    volatile uint8_t MCR;      /* Modem Control */
    volatile uint8_t LSR;      /* Line Status */
    volatile uint8_t MSR;      /* Modem Status */
    volatile uint8_t SCR;      /* Scratch */
} UART_Regs;

/* GPIO Register Map */
typedef struct {
    volatile uint32_t REVISION;
    volatile uint32_t SYSCONFIG;
    volatile uint32_t IRQSTATUS_RAW_0;
    volatile uint32_t IRQSTATUS_0;
    volatile uint32_t IRQSTATUS_SET_0;
    volatile uint32_t IRQSTATUS_CLR_0;
    volatile uint32_t IRQWAKEN_0;
    volatile uint32_t reserved[16];
    volatile uint32_t DATAOUT;
    volatile uint32_t DATAIN;
    volatile uint32_t DIR;
    volatile uint32_t SETDATAOUT;
    volatile uint32_t CLEARDATAOUT;
} GPIO_Regs;

static UART_Regs* uart0 = (UART_Regs*)UART0_BASE;
static GPIO_Regs* gpio1 = (GPIO_Regs*)GPIO1_BASE;

void uart_init(void) {
    uart0->LCR = 0x80;  /* Enable DLAB */
    uart0->RBR_THR = 0x1A;
    uart0->IER = 0x00;
    uart0->LCR = 0x03;  /* 8N1 */
    uart0->FCR_IIR = 0x07;  /* Enable FIFO */
}

void uart_putc(char c) {
    while ((uart0->LSR & 0x20) == 0);
    uart0->RBR_THR = c;
}

void gpio_set_direction(uint32_t pin, bool is_output) {
    if (is_output) {
        gpio1->DIR |= (1U << pin);
    } else {
        gpio1->DIR &= ~(1U << pin);
    }
}

void gpio_write(uint32_t pin, bool value) {
    if (value) {
        gpio1->SETDATAOUT = (1U << pin);
    } else {
        gpio1->CLEARDATAOUT = (1U << pin);
    }
}

void soc_init(void) {
    uart_init();
    gpio_set_direction(8, true);
    gpio_write(8, true);

    char* msg = "[AM335x] Sitara BSP Boot Complete\\r\\n";
    while (*msg) uart_putc(*msg++);
}

int main(void) {
    soc_init();
    while (1) {
        for (volatile int i = 0; i < 2000000; i++);
        gpio_write(8, false);
        for (volatile int i = 0; i < 2000000; i++);
        gpio_write(8, true);
    }
    return 0;
}`,
    deviceTreeCode: `/dts-v1/;
/ {
    compatible = "ti,am335x-bone";
    model = "TI Sitara AM335x GenAI BSP";
    #address-cells = <1>;
    #size-cells = <1>;

    cpus {
        #address-cells = <1>;
        #size-cells = <0>;

        cpu@0 {
            device_type = "cpu";
            compatible = "arm,cortex-a8";
            reg = <0x0>;
            clock-frequency = <720000000>;
        };
    };

    memory@80000000 {
        device_type = "memory";
        reg = <0x80000000 0x20000000>;
    };

    uart0: serial@44e09000 {
        compatible = "ti,omap3-uart";
        reg = <0x44e09000 0x100>;
        interrupts = <72>;
        clock-frequency = <48000000>;
        status = "okay";
    };

    gpio1: gpio@4804c000 {
        compatible = "ti,omap4-gpio";
        reg = <0x4804c000 0x100>;
        interrupts = <98>;
        gpio-controller;
        #gpio-cells = <2>;
        status = "okay";
    };

    i2c1: i2c@4802a000 {
        compatible = "ti,omap4-i2c";
        reg = <0x4802a000 0x100>;
        interrupts = <62>;
        clock-frequency = <400000>;
        #address-cells = <1>;
        #size-cells = <0>;
        status = "okay";
    };

    spi0: spi@48030000 {
        compatible = "ti,omap4-mcspi";
        reg = <0x48030000 0x1000>;

        interrupts = <65>;
        #address-cells = <1>;
        #size-cells = <0>;
        status = "okay";
    };

    mmc0: mmc@48060000 {
        compatible = "ti,omap4-hsmmc";
        reg = <0x48060000 0x100>;
        interrupts = <64>;
        status = "okay";
    };

    gpmc: gpmc@50000000 {
        compatible = "ti,am3352-gpmc";
        reg = <0x50000000 0x100>;
        status = "disabled";
    };
};`,
  },
  {
    id: 'stm32h7',
    name: 'STM32H7',
    vendor: 'STMicroelectronics',
    logoType: 'st' as const,
    architecture: 'ARM Cortex-M7',
    frequency: '480 MHz',
    peripherals: [
      { id: '1', peripheralBlock: 'USART1', physicalPinMapping: 'PA9/PA10', clockNetIndicator: true, baseAddress: '0x40013800' },
      { id: '2', peripheralBlock: 'GPIOA', physicalPinMapping: 'PA[0:15]', clockNetIndicator: true, baseAddress: '0x58020000' },
      { id: '3', peripheralBlock: 'I2C1', physicalPinMapping: 'PB8/PB9', clockNetIndicator: true, baseAddress: '0x40005400' },
      { id: '4', peripheralBlock: 'SPI1', physicalPinMapping: 'PA5/PA6/PA7', clockNetIndicator: true, baseAddress: '0x40013000' },
      { id: '5', peripheralBlock: 'TIM1', physicalPinMapping: 'PA8/PA9/PA10', clockNetIndicator: true, baseAddress: '0x40016C00' },
      { id: '6', peripheralBlock: 'ADC1', physicalPinMapping: 'PA[0:3]', clockNetIndicator: true, baseAddress: '0x40022400' },
      { id: '7', peripheralBlock: 'SDMMC1', physicalPinMapping: 'PC[8:12]', clockNetIndicator: true, baseAddress: '0x52007000' },
      { id: '8', peripheralBlock: 'FDCAN1', physicalPinMapping: 'PA11/PA12', clockNetIndicator: false, baseAddress: '0x4000A000' },
    ],
    bareMetalCode: `/**
 * STM32H7 Bare Metal Driver
 * Generated by GenAI BSP Platform
 */

#include <stdint.h>
#include <stdbool.h>

#define USART1_BASE        0x40013800
#define GPIOA_BASE         0x58020000
#define I2C1_BASE          0x40005400
#define SPI1_BASE          0x40013000
#define TIM1_BASE          0x40016C00
#define ADC1_BASE          0x40022400
#define SDMMC1_BASE        0x52007000
#define FDCAN1_BASE        0x4000A000
#define RCC_BASE           0x58024400

/* RCC Register Map */
typedef struct {
    volatile uint32_t CR;
    volatile uint32_t HSICFGR;
    volatile uint32_t CRRCR;
    volatile uint32_t CSICFGR;
    volatile uint32_t CFGR;
    volatile uint32_t D1CFGR;
    volatile uint32_t D2CFGR;
    volatile uint32_t D3CFGR;
    volatile uint32_t reserved1;
    volatile uint32_t PLLCKSELR;
    volatile uint32_t PLLCFGR;
    volatile uint32_t PLL1DIVR;
    volatile uint32_t PLL1FRACR;
    volatile uint32_t PLL2DIVR;
    volatile uint32_t PLL2FRACR;
    volatile uint32_t PLL3DIVR;
} RCC_Regs;

/* USART Register Map */
typedef struct {
    volatile uint32_t CR1;
    volatile uint32_t CR2;
    volatile uint32_t CR3;
    volatile uint32_t BRR;
    volatile uint32_t GTPR;
    volatile uint32_t RTOR;
    volatile uint32_t RQR;
    volatile uint32_t ISR;
    volatile uint32_t ICR;
    volatile uint32_t RDR;
    volatile uint32_t TDR;
} USART_Regs;

/* GPIO Register Map */
typedef struct {
    volatile uint32_t MODER;
    volatile uint32_t OTYPER;
    volatile uint32_t OSPEEDR;
    volatile uint32_t PUPDR;
    volatile uint32_t IDR;
    volatile uint32_t ODR;
    volatile uint32_t BSRR;
    volatile uint32_t LCKR;
    volatile uint32_t AFR[2];
} GPIO_Regs;

static USART_Regs* usart1 = (USART_Regs*)USART1_BASE;
static GPIO_Regs* gpioa = (GPIO_Regs*)GPIOA_BASE;
static RCC_Regs* rcc = (RCC_Regs*)RCC_BASE;

void rcc_init(void) {
    rcc->CR |= (1 << 0);  /* Enable HSI */
    while (!(rcc->CR & (1 << 2)));
}

void usart_init(uint32_t baudrate) {
    usart1->BRR = 64000000 / baudrate;
    usart1->CR1 = (1 << 0) | (1 << 2) | (1 << 3) | (1 << 5);
}

void usart_putc(char c) {
    while (!(usart1->ISR & (1 << 7)));
    usart1->TDR = c;
}

void gpio_set_mode(uint32_t pin, uint32_t mode) {
    gpioa->MODER &= ~(3 << (pin * 2));
    gpioa->MODER |= (mode << (pin * 2));
}

void gpio_write(uint32_t pin, bool value) {
    if (value) {
        gpioa->BSRR = (1 << pin);
    } else {
        gpioa->BSRR = (1 << (pin + 16));
    }
}

void system_init(void) {
    rcc_init();
    usart_init(115200);
    gpio_set_mode(5, 1);

    char* msg = "[STM32H7] HAL Initialization Sequence Complete\\r\\n";
    while (*msg) usart_putc(*msg++);
}

int main(void) {
    system_init();
    while (1) {
        for (volatile int i = 0; i < 500000; i++);
        gpio_write(5, true);
        for (volatile int i = 0; i < 500000; i++);
        gpio_write(5, false);
    }
    return 0;
}`,
    deviceTreeCode: `/dts-v1/;
/ {
    compatible = "st,stm32h7";
    model = "STM32H7 GenAI BSP";
    #address-cells = <1>;
    #size-cells = <1>;

    chosen {
        bootargs = "console=ttySTM0,115200";
        stdout-path = &usart1;
    };

    cpus {
        #address-cells = <1>;
        #size-cells = <0>;

        cpu@0 {
            device_type = "cpu";
            compatible = "arm,cortex-m7";
            reg = <0x0>;
            clock-frequency = <480000000>;
        };
    };

    sram: memory@20000000 {
        device_type = "memory";
        reg = <0x20000000 0x40000>;
    };

    usart1: serial@40013800 {
        compatible = "st,stm32h7-usart";
        reg = <0x40013800 0x400>;
        interrupts = <37>;
        clocks = <&rcc USART1_CLK>;
        pinctrl-names = "default";
        pinctrl-0 = <&usart1_pins>;
        status = "okay";
    };

    gpioa: gpio@58020000 {
        compatible = "st,stm32h7-gpio";
        reg = <0x58020000 0x400>;
        gpio-controller;
        #gpio-cells = <2>;
        status = "okay";
    };

    i2c1: i2c@40005400 {
        compatible = "st,stm32h7-i2c";
        reg = <0x40005400 0x400>;
        interrupts = <31>;
        clock-frequency = <400000>;
        #address-cells = <1>;
        #size-cells = <0>;
        status = "okay";
    };

    spi1: spi@40013000 {
        compatible = "st,stm32h7-spi";
        reg = <0x40013000 0x400>;
        interrupts = <35>;
        #address-cells = <1>;
        #size-cells = <0>;
        status = "okay";
    };

    tim1: timer@40016c00 {
        compatible = "st,stm32h7-tim";
        reg = <0x40016c00 0x400>;
        status = "okay";
    };

    adc1: adc@40022400 {
        compatible = "st,stm32h7-adc";
        reg = <0x40022400 0x100>;
        interrupts = <18>;
        status = "okay";
    };

    rcc: rcc@58024400 {
        compatible = "st,stm32h7-rcc";
        reg = <0x58024400 0x400>;
        #clock-cells = <1>;
    };

    pinctrl {
        usart1_pins: usart1-0 {
            pins {
                pinmux = <STM32_PINMUX('A', 9, AF7)>,
                         <STM32_PINMUX('A', 10, AF7)>;
                bias-pull-up;
            };
        };
    };
};`,
  },
  {
    id: 'nvidia-jetson-orin-nx',
    name: 'NVIDIA Jetson Orin NX',
    vendor: 'NVIDIA',
    logoType: 'nvidia' as const,
    architecture: 'ARM Cortex-A78AE',
    frequency: '2.0 GHz',
    peripherals: [
      { id: '1', peripheralBlock: 'UART0', physicalPinMapping: 'J41[8:10]', clockNetIndicator: true, baseAddress: '0x03100000' },
      { id: '2', peripheralBlock: 'I2C1', physicalPinMapping: 'J41[3:5]', clockNetIndicator: true, baseAddress: '0x03160000' },
      { id: '3', peripheralBlock: 'SPI1', physicalPinMapping: 'J41[19:26]', clockNetIndicator: true, baseAddress: '0x03210000' },
      { id: '4', peripheralBlock: 'GPIO', physicalPinMapping: 'J41[7:40]', clockNetIndicator: true, baseAddress: '0x02200000' },
      { id: '5', peripheralBlock: 'CSI0', physicalPinMapping: 'CAM0[1:10]', clockNetIndicator: true, baseAddress: '0x13000000' },
      { id: '6', peripheralBlock: 'PCIe0', physicalPinMapping: 'M2KEY[1:52]', clockNetIndicator: true, baseAddress: '0x14100000' },
      { id: '7', peripheralBlock: 'USB3', physicalPinMapping: 'USB[1:20]', clockNetIndicator: true, baseAddress: '0x03610000' },
      { id: '8', peripheralBlock: 'SDMMC', physicalPinMapping: 'SD[1:10]', clockNetIndicator: true, baseAddress: '0x03400000' },
      { id: '9', peripheralBlock: 'GigE', physicalPinMapping: 'ETH[1:12]', clockNetIndicator: true, baseAddress: '0x02490000' },
      { id: '10', peripheralBlock: 'CAN0', physicalPinMapping: 'J30[3:5]', clockNetIndicator: false, baseAddress: '0x0C310000' },
    ],
    bareMetalCode: `/**
 * NVIDIA Jetson Orin NX Bare Metal Driver
 * Generated by GenAI BSP Platform
 */

#include <stdint.h>
#include <stdbool.h>

#define UART0_BASE          0x03100000
#define I2C1_BASE           0x03160000
#define SPI1_BASE           0x03210000
#define GPIO_BASE           0x02200000
#define CSI0_BASE           0x13000000
#define PCIE0_BASE          0x14100000
#define USB3_BASE           0x03610000
#define SDMMC_BASE          0x03400000
#define GIGE_BASE           0x02490000
#define CAN0_BASE           0x0C310000

/* UART Register Map - Tegra UARTD */
typedef struct {
    volatile uint32_t THR_DLAB;  /* TX Holding / Divisor LSB */
    volatile uint32_t IER_DLAB;  /* Int Enable / Divisor MSB */
    volatile uint32_t FCR_IIR;   /* FIFO Control / Int Ident */
    volatile uint32_t LCR;       /* Line Control */
    volatile uint32_t MCR;       /* Modem Control */
    volatile uint32_t LSR;       /* Line Status */
    volatile uint32_t MSR;       /* Modem Status */
    volatile uint32_t SPR;       /* Scratch Pad */
} UART_Regs;

static UART_Regs* uart0 = (UART_Regs*)UART0_BASE;

void uart_init(void) {
    uart0->LCR = 0x80;   /* DLAB enable */
    uart0->THR_DLAB = 0x04; /* Divisor = 4 for 115200 @ 60MHz */
    uart0->IER_DLAB = 0x00;
    uart0->LCR = 0x03;   /* 8N1 */
    uart0->FCR_IIR = 0x07; /* Enable FIFO */
}

void uart_send(char c) {
    while (!(uart0->LSR & 0x20));
    uart0->THR_DLAB = c;
}

void system_init(void) {
    uart_init();
    char* msg = "[Orin NX] Jetson BSP Initialized\\r\\n";
    while (*msg) uart_send(*msg++);
}

int main(void) {
    system_init();
    while (1) { /* application loop */ }
    return 0;
}`,
    deviceTreeCode: `/dts-v1/;
/ {
    compatible = "nvidia,p3767", "nvidia,tegra234";
    model = "NVIDIA Jetson Orin NX GenAI BSP";
    #address-cells = <2>;
    #size-cells = <2>;

    cpus {
        #address-cells = <1>;
        #size-cells = <0>;
        cpu@0 {
            device_type = "cpu";
            compatible = "arm,cortex-a78ae";
            reg = <0x0>;
            clock-frequency = <2000000000>;
        };
    };

    memory@80000000 {
        device_type = "memory";
        reg = <0x0 0x80000000 0x1 0x00000000>;
    };

    serial@3100000 {
        compatible = "nvidia,tegra234-hsuart";
        reg = <0x0 0x03100000 0x0 0x10000>;
        interrupts = <0x0 0x70 0x4>;
        clock-names = "serial";
        status = "okay";
    };

    i2c@3160000 {
        compatible = "nvidia,tegra234-i2c";
        reg = <0x0 0x03160000 0x0 0x10000>;
        clock-frequency = <400000>;
        #address-cells = <1>;
        #size-cells = <0>;
        status = "okay";
    };

    gpio@2200000 {
        compatible = "nvidia,tegra234-gpio";
        reg = <0x0 0x02200000 0x0 0x10000>;
        gpio-controller;
        #gpio-cells = <2>;
        status = "okay";
    };

    pcie@14100000 {
        compatible = "nvidia,tegra234-pcie";
        reg = <0x0 0x14100000 0x0 0x100000>;
        status = "okay";
    };
};`,
  },
  {
    id: 'samsung-exynos-5422',
    name: 'Samsung Exynos 5422',
    vendor: 'Samsung',
    logoType: 'samsung' as const,
    architecture: 'ARM Cortex-A15 + A7',
    frequency: '2.1 GHz',
    peripherals: [
      { id: '1', peripheralBlock: 'UART2', physicalPinMapping: 'GPA1[4:5]', clockNetIndicator: true, baseAddress: '0x12C20000' },
      { id: '2', peripheralBlock: 'I2C0', physicalPinMapping: 'GPB3[0:1]', clockNetIndicator: true, baseAddress: '0x12C60000' },
      { id: '3', peripheralBlock: 'SPI0', physicalPinMapping: 'GPA2[0:3]', clockNetIndicator: true, baseAddress: '0x12D20000' },
      { id: '4', peripheralBlock: 'GPIO', physicalPinMapping: 'GPX[0:3]', clockNetIndicator: true, baseAddress: '0x13400000' },
      { id: '5', peripheralBlock: 'USB2', physicalPinMapping: 'USB[1:5]', clockNetIndicator: true, baseAddress: '0x12110000' },
      { id: '6', peripheralBlock: 'MMC2', physicalPinMapping: 'GPK2[0:6]', clockNetIndicator: true, baseAddress: '0x12220000' },
      { id: '7', peripheralBlock: 'I2S0', physicalPinMapping: 'GPZ[0:6]', clockNetIndicator: true, baseAddress: '0x03830000' },
      { id: '8', peripheralBlock: 'PWM', physicalPinMapping: 'GPD0[0:3]', clockNetIndicator: false, baseAddress: '0x12DD0000' },
      { id: '9', peripheralBlock: 'ADC', physicalPinMapping: 'AIN[0:3]', clockNetIndicator: false, baseAddress: '0x12D10000' },
    ],
    bareMetalCode: `/**
 * Samsung Exynos 5422 Bare Metal Driver
 * Generated by GenAI BSP Platform
 */

#include <stdint.h>
#include <stdbool.h>

#define UART2_BASE          0x12C20000
#define I2C0_BASE           0x12C60000
#define SPI0_BASE           0x12D20000
#define GPIO_BASE           0x13400000
#define USB2_BASE           0x12110000
#define MMC2_BASE           0x12220000
#define I2S0_BASE           0x03830000
#define PWM_BASE            0x12DD0000
#define ADC_BASE            0x12D10000

/* UART Register Map - Exynos S5PV210 Compatible */
typedef struct {
    volatile uint32_t ULCON;   /* Line Control */
    volatile uint32_t UCON;    /* Control */
    volatile uint32_t UFCON;   /* FIFO Control */
    volatile uint32_t UMCON;   /* Modem Control */
    volatile uint32_t UTRSTAT; /* TX/RX Status */
    volatile uint32_t UERSTAT; /* Error Status */
    volatile uint32_t UFSTAT;  /* FIFO Status */
    volatile uint32_t UMSTAT;  /* Modem Status */
    volatile uint32_t UTXH;    /* TX Buffer */
    volatile uint32_t URXH;    /* RX Buffer */
    volatile uint32_t UBRDIV;  /* Baud Rate Divisor */
} UART_Regs;

static UART_Regs* uart2 = (UART_Regs*)UART2_BASE;

void uart_init(void) {
    uart2->ULCON = 0x03;    /* 8N1 */
    uart2->UCON  = 0x245;   /* RX/TX interrupt mode */
    uart2->UFCON = 0x01;    /* Enable FIFO */
    uart2->UBRDIV = 0x23;   /* 115200 baud @ 100MHz */
}

void uart_putc(char c) {
    while (!(uart2->UTRSTAT & 0x02));
    uart2->UTXH = c;
}

void system_init(void) {
    uart_init();
    char* msg = "[Exynos 5422] BSP Initialization OK\\r\\n";
    while (*msg) uart_putc(*msg++);
}

int main(void) {
    system_init();
    while (1) { /* application loop */ }
    return 0;
}`,
    deviceTreeCode: `/dts-v1/;
/ {
    compatible = "samsung,exynos5422";
    model = "Samsung Exynos 5422 GenAI BSP";
    #address-cells = <1>;
    #size-cells = <1>;

    cpus {
        #address-cells = <1>;
        #size-cells = <0>;

        cpu@0 {
            device_type = "cpu";
            compatible = "arm,cortex-a15";
            reg = <0x0>;
            clock-frequency = <2100000000>;
        };

        cpu@4 {
            device_type = "cpu";
            compatible = "arm,cortex-a7";
            reg = <0x4>;
            clock-frequency = <1500000000>;
        };
    };

    memory@40000000 {
        device_type = "memory";
        reg = <0x40000000 0x80000000>;
    };

    serial@12c20000 {
        compatible = "samsung,exynos4210-uart";
        reg = <0x12c20000 0x100>;
        interrupts = <0 53 0>;
        clock-names = "uart", "clk_uart_baud0";
        status = "okay";
    };

    i2c@12c60000 {
        compatible = "samsung,s3c2440-i2c";
        reg = <0x12c60000 0x100>;
        interrupts = <0 56 0>;
        clock-frequency = <400000>;
        #address-cells = <1>;
        #size-cells = <0>;
        status = "okay";
    };

    gpio@13400000 {
        compatible = "samsung,exynos5420-pinctrl";
        reg = <0x13400000 0x1000>;
        interrupts = <0 46 0>;
        gpio-controller;
        #gpio-cells = <2>;
        status = "okay";
    };

    mmc@12220000 {
        compatible = "samsung,exynos5420-dw-mshc";
        reg = <0x12220000 0x1000>;
        interrupts = <0 77 0>;
        status = "okay";
    };
};`,
  },
  {
    id: 'nxp-imx8m-plus',
    name: 'NXP i.MX 8M Plus',
    vendor: 'NXP',
    logoType: 'nxp' as const,
    architecture: 'ARM Cortex-A53 + M7',
    frequency: '1.8 GHz',
    peripherals: [
      { id: '1', peripheralBlock: 'UART2', physicalPinMapping: 'PAD_UART2[TX/RX]', clockNetIndicator: true, baseAddress: '0x30890000' },
      { id: '2', peripheralBlock: 'I2C1', physicalPinMapping: 'PAD_I2C1[SCL/SDA]', clockNetIndicator: true, baseAddress: '0x30A20000' },
      { id: '3', peripheralBlock: 'SPI1', physicalPinMapping: 'PAD_ECSPI1[MOSI:CS]', clockNetIndicator: true, baseAddress: '0x30820000' },
      { id: '4', peripheralBlock: 'GPIO1', physicalPinMapping: 'PAD_GPIO1[IO00:IO15]', clockNetIndicator: true, baseAddress: '0x30200000' },
      { id: '5', peripheralBlock: 'USDHC2', physicalPinMapping: 'PAD_SD2[CLK:D7]', clockNetIndicator: true, baseAddress: '0x30B50000' },
      { id: '6', peripheralBlock: 'USB1', physicalPinMapping: 'USB1_OTG[DM:DP]', clockNetIndicator: true, baseAddress: '0x38100000' },
      { id: '7', peripheralBlock: 'ENET1', physicalPinMapping: 'PAD_ENET1[MDC:RXD3]', clockNetIndicator: true, baseAddress: '0x30BE0000' },
      { id: '8', peripheralBlock: 'SAI3', physicalPinMapping: 'PAD_SAI3[TXD:RXD]', clockNetIndicator: false, baseAddress: '0x302C0000' },
    ],
    bareMetalCode: `/**
 * NXP i.MX 8M Plus Bare Metal Driver
 * Generated by GenAI BSP Platform
 */

#include <stdint.h>
#include <stdbool.h>

#define UART2_BASE          0x30890000
#define I2C1_BASE           0x30A20000
#define SPI1_BASE           0x30820000
#define GPIO1_BASE          0x30200000
#define USDHC2_BASE         0x30B50000
#define USB1_BASE           0x38100000
#define ENET1_BASE          0x30BE0000
#define SAI3_BASE           0x302C0000

/* UART Register Map - i.MX8 LPUART */
typedef struct {
    volatile uint32_t VERID;  /* Version ID */
    volatile uint32_t PARAM;  /* Parameter */
    volatile uint32_t GLOBAL; /* Global */
    volatile uint32_t PINCFG; /* Pin Config */
    volatile uint32_t BAUD;   /* Baud Rate */
    volatile uint32_t STAT;   /* Status */
    volatile uint32_t CTRL;   /* Control */
    volatile uint32_t DATA;   /* Data */
    volatile uint32_t MATCH;  /* Match Address */
    volatile uint32_t MODIR;  /* Modem IrDA */
    volatile uint32_t FIFO;   /* FIFO Control */
    volatile uint32_t WATER;  /* Watermark */
} UART_Regs;

static UART_Regs* uart2 = (UART_Regs*)UART2_BASE;

void uart_init(void) {
    uart2->CTRL = 0;
    uart2->BAUD = 0x0F000004; /* 115200 baud */
    uart2->CTRL = (1 << 19) | (1 << 18); /* TE | RE */
}

void uart_putc(char c) {
    while (!(uart2->STAT & (1 << 23)));
    uart2->DATA = c;
}

void system_init(void) {
    uart_init();
    char* msg = "[i.MX 8M Plus] NXP BSP Initialized\\r\\n";
    while (*msg) uart_putc(*msg++);
}

int main(void) {
    system_init();
    while (1) { /* application loop */ }
    return 0;
}`,
    deviceTreeCode: `/dts-v1/;
/ {
    compatible = "fsl,imx8mp";
    model = "NXP i.MX 8M Plus GenAI BSP";
    #address-cells = <2>;
    #size-cells = <2>;

    cpus {
        #address-cells = <1>;
        #size-cells = <0>;

        cpu@0 {
            device_type = "cpu";
            compatible = "arm,cortex-a53";
            reg = <0x0>;
            clock-frequency = <1800000000>;
        };

        cpu@100 {
            device_type = "cpu";
            compatible = "arm,cortex-m7";
            reg = <0x100>;
            clock-frequency = <800000000>;
        };
    };

    memory@40000000 {
        device_type = "memory";
        reg = <0x0 0x40000000 0x0 0x80000000>;
    };

    uart2: serial@30890000 {
        compatible = "fsl,imx8mp-lpuart", "fsl,imx7ulp-lpuart";
        reg = <0x0 0x30890000 0x0 0x10000>;
        interrupts = <0 28 4>;
        clock-names = "ipg", "per";
        status = "okay";
    };

    i2c1: i2c@30a20000 {
        compatible = "fsl,imx8mp-i2c", "fsl,imx21-i2c";
        reg = <0x0 0x30a20000 0x0 0x10000>;
        interrupts = <0 35 4>;
        clock-frequency = <400000>;
        #address-cells = <1>;
        #size-cells = <0>;
        status = "okay";
    };

    gpio1: gpio@30200000 {
        compatible = "fsl,imx8mp-gpio", "fsl,imx35-gpio";
        reg = <0x0 0x30200000 0x0 0x10000>;
        interrupts = <0 64 4>, <0 65 4>;
        gpio-controller;
        #gpio-cells = <2>;
        status = "okay";
    };

    usdhc2: mmc@30b50000 {
        compatible = "fsl,imx8mp-usdhc", "fsl,imx7d-usdhc";
        reg = <0x0 0x30b50000 0x0 0x10000>;
        interrupts = <0 23 4>;
        status = "okay";
    };

    fec1: ethernet@30be0000 {
        compatible = "fsl,imx8mp-fec", "fsl,imx6sx-fec";
        reg = <0x0 0x30be0000 0x0 0x10000>;
        interrupts = <0 118 4>;
        phy-mode = "rgmii-id";
        status = "okay";
    };
};`,
  },
  {
    id: 'xilinx-microblaze-mcu',
    name: 'AMD MicroBlaze MCS',
    vendor: 'AMD Xilinx',
    logoType: 'xilinx' as const,
    architecture: 'MicroBlaze 32-bit Soft Processor',
    frequency: '100 MHz',
    peripherals: [
      { id: '1', peripheralBlock: 'axi_uartlite_0', physicalPinMapping: 'RX/TX Pins', clockNetIndicator: true, baseAddress: '0x40600000' },
      { id: '2', peripheralBlock: 'axi_gpio_0', physicalPinMapping: 'LED_Pins[0:7]', clockNetIndicator: false, baseAddress: '0x40000000' },
      { id: '3', peripheralBlock: 'axi_timer_0', physicalPinMapping: 'PWM_Output', clockNetIndicator: true, baseAddress: '0x41C00000' },
    ],
    bareMetalCode: `/**
 * AMD MicroBlaze Soft Core Bare Metal Firmware
 * Generated by GenAI BSP Platform
 */

#include "xparameters.h"
#include "xuartlite.h"
#include "xgpio.h"
#include "xtmrctr.h"

#define UARTLITE_BASEADDR  XPAR_AXI_UARTLITE_0_BASEADDR
#define GPIO_BASEADDR      XPAR_AXI_GPIO_0_BASEADDR
#define TIMER_BASEADDR     XPAR_AXI_TIMER_0_BASEADDR

static XUartLite uart;
static XGpio gpio;
static XTmrCtr timer;

int main(void) {
    // Initialize UARTLite
    XUartLite_Initialize(&uart, UARTLITE_BASEADDR);
    
    // Initialize GPIO
    XGpio_Initialize(&gpio, GPIO_BASEADDR);
    XGpio_SetDataDirection(&gpio, 1, 0x00); // Set channel 1 as output

    // Print banner
    XUartLite_SendByte(UARTLITE_BASEADDR, 'M');
    XUartLite_SendByte(UARTLITE_BASEADDR, 'B');
    XUartLite_SendByte(UARTLITE_BASEADDR, '\\n');

    while(1) {
        XGpio_DiscreteWrite(&gpio, 1, 0xFF);
        for(volatile int i=0; i<100000; i++);
        XGpio_DiscreteWrite(&gpio, 1, 0x00);
        for(volatile int i=0; i<100000; i++);
    }
    return 0;
}`,
    deviceTreeCode: `/dts-v1/;
/ {
    #address-cells = <1>;
    #size-cells = <1>;
    model = "AMD MicroBlaze MCS soft processor";
    compatible = "xlnx,microblaze-32";
    cpus {
        cpu@0 {
            compatible = "xlnx,microblaze-11.0";
            device_type = "cpu";
            reg = <0>;
        };
    };
    amba {
        #address-cells = <1>;
        #size-cells = <1>;
        compatible = "simple-bus";
        ranges;
        axi_uartlite_0: serial@40600000 {
            compatible = "xlnx,axi-uartlite-2.0", "xlnx,xps-uartlite-1.00.a";
            reg = <0x40600000 0x10000>;
            interrupts = <0 0 2>;
            status = "okay";
        };
        axi_gpio_0: gpio@40000000 {
            compatible = "xlnx,axi-gpio-2.0", "xlnx,xps-gpio-1.00.a";
            reg = <0x40000000 0x10000>;
            gpio-controller;
            #gpio-cells = <2>;
            status = "okay";
        };
    };
};`,
  },
];

export function generateBareMetalCode(peripherals: { peripheralBlock: string; baseAddress: string }[]): string {
  let code = `/**
 * Custom Bare Metal Driver
 * Generated by GenAI BSP Platform
 * Peripheral Count: ${peripherals.length}
 */

#include <stdint.h>
#include <stdbool.h>

`;

  peripherals.forEach(p => {
    code += `#define ${p.peripheralBlock.toUpperCase().replace(/[^A-Z0-9]/g, '_')}_BASE    ${p.baseAddress}\n`;
  });

  code += `
/* Register Map Structures */
typedef struct {
    volatile uint32_t CR;
    volatile uint32_t SR;
    volatile uint32_t DR;
    volatile uint32_t reserved;
} Generic_Regs;

void system_init(void) {
    /* Hardware initialization sequence */
}

int main(void) {
    system_init();
    while (1) {
        /* Application loop */
    }
    return 0;
}`;

  return code;
}

export function generateDeviceTreeCode(peripherals: { peripheralBlock: string; baseAddress: string }[]): string {
  let code = `/dts-v1/;
/ {
    compatible = "custom,bsp-platform";
    model = "Custom GenAI BSP";
    #address-cells = <1>;
    #size-cells = <1>;

    chosen {
        stdout-path = &serial;
    };

    cpus {
        #address-cells = <1>;
        #size-cells = <0>;

        cpu@0 {
            device_type = "cpu";
            compatible = "arm,cortex-a53";
            reg = <0x0>;
        };
    };

    memory@40000000 {
        device_type = "memory";
        reg = <0x40000000 0x10000000>;
    };

`;

  peripherals.forEach((p, idx) => {
    const name = p.peripheralBlock.toLowerCase();
    code += `    ${name}: peripheral${idx + 1}@${p.baseAddress.replace('0x', '')} {
        compatible = "custom,peripheral";
        reg = <${p.baseAddress} 0x100>;
        status = "okay";
    };

`;
  });

  code += `};`;
  return code;
}

// Dynamic Enrichment of Presets with Advanced EDA/Processor Architecture properties
export const hardwarePresets: PlatformPreset[] = rawPresets.map((preset) => {
  const isXilinx = preset.id.includes('zynq') || preset.vendor.toLowerCase() === 'xilinx';
  const isST = preset.id.includes('stm') || preset.vendor.toLowerCase() === 'stmicroelectronics';

  const memoryType = isXilinx ? 'DDR4 SDRAM' : isST ? 'Internal SRAM' : 'LPDDR4 SDRAM';
  const clockSource = isXilinx ? 'AXI Clock (100 MHz)' : isST ? 'HSE (8 MHz PLL)' : 'System PLL (100 MHz)';
  const resetController = isXilinx ? 'PS Reset System' : isST ? 'RCC Reset' : 'SoC Reset Controller';
  const interruptController = isXilinx ? 'GIC (Generic Interrupt Controller)' : isST ? 'NVIC (Nested Vectored Interrupt Controller)' : 'GIC-v3';
  const axiInterconnect = isXilinx ? 'AXI SmartConnect' : isST ? 'AHB/APB Matrix' : 'AXI Coherent Interconnect';
  const bootDevice = isXilinx ? 'QSPI Flash / SD Card' : isST ? 'Internal Flash' : 'eMMC / SPI Flash';
  const operatingSystems = isST ? ['Bare Metal', 'FreeRTOS'] : ['Bare Metal', 'FreeRTOS', 'Linux'];
  const vivadoVersion = isXilinx ? '2025.2' : 'N/A';
  const vitisVersion = isXilinx ? '2025.2' : 'N/A';

  const peripherals = preset.peripherals.map((p, idx) => {
    let driverName = 'custom_driver';
    let interruptNumber = 16 + idx;
    
    if (isXilinx) {
      const isZynq7000 = preset.id.includes('7000');
      if (p.peripheralBlock.toLowerCase().includes('uart')) {
        driverName = 'XUartPs';
        interruptNumber = isZynq7000 ? 53 : 53 + idx;
      } else if (p.peripheralBlock.toLowerCase().includes('gpio')) {
        driverName = 'XGpioPs';
        interruptNumber = isZynq7000 ? 52 : 121 + idx;
      } else if (p.peripheralBlock.toLowerCase().includes('i2c')) {
        driverName = 'XIicPs';
        interruptNumber = isZynq7000 ? 57 : 113 + idx;
      } else if (p.peripheralBlock.toLowerCase().includes('spi')) {
        driverName = 'XSpiPs';
        interruptNumber = isZynq7000 ? 58 : 115 + idx;
      } else if (p.peripheralBlock.toLowerCase().includes('can')) {
        driverName = 'XCanPs';
        interruptNumber = isZynq7000 ? 59 : 104 + idx;
      } else if (p.peripheralBlock.toLowerCase().includes('eth')) {
        driverName = 'XEmacPs';
        interruptNumber = isZynq7000 ? 54 : 120 + idx;
      } else if (p.peripheralBlock.toLowerCase().includes('usb')) {
        driverName = 'XUsbPs';
        interruptNumber = isZynq7000 ? 55 : 125 + idx;
      }
    } else if (isST) {
      if (p.peripheralBlock.toLowerCase().includes('usart') || p.peripheralBlock.toLowerCase().includes('uart')) {
        driverName = 'HAL_UART';
        interruptNumber = 37 + idx;
      } else if (p.peripheralBlock.toLowerCase().includes('gpio')) {
        driverName = 'HAL_GPIO';
      } else if (p.peripheralBlock.toLowerCase().includes('i2c')) {
        driverName = 'HAL_I2C';
        interruptNumber = 31 + idx;
      } else if (p.peripheralBlock.toLowerCase().includes('spi')) {
        driverName = 'HAL_SPI';
        interruptNumber = 35 + idx;
      } else if (p.peripheralBlock.toLowerCase().includes('tim')) {
        driverName = 'HAL_TIM';
        interruptNumber = 28 + idx;
      } else if (p.peripheralBlock.toLowerCase().includes('adc')) {
        driverName = 'HAL_ADC';
        interruptNumber = 18 + idx;
      }
    }

    const confidence = (driverName !== 'custom_driver' && interruptNumber > 0) ? 98 : 92;

    return {
      ...p,
      driverName,
      interruptNumber,
      status: 'Active' as const,
      confidence,
    };
  });

  return {
    ...preset,
    memoryType,
    clockSource,
    resetController,
    interruptController,
    axiInterconnect,
    bootDevice,
    operatingSystems,
    vivadoVersion,
    vitisVersion,
    peripherals,
  };
});

